[package]
name = "civ_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
env_logger.workspace = true
log.workspace = true
rayon.workspace = true
num_cpus.workspace = true
crossbeam.workspace = true
